markdown: kramdown
title: snook.pub
domainroot: http://snook.pub
fb:
  title: snook.pub
  image: '/static/images/face.jpg'
  description: "This site is where I record thoughts and ideas. It's a mix of one-off ideas for apps or projects, casual musings, and repeat commentary on developing thoughts around potential projects that really capture my imagination and passion and seem valuable for the world."
  site_name: "Michael Snook's Weblog And Project Pad"
exclude:
 - node_modules
 - README.md
 - CNAME
 - Gruntfile.js
 - humans.txt
 - LICENSE
 - stylesheets
 - scss
 - bower_components
 - package.json
 - bower.json
footer:
 - text: home
   icon: home
   href: /
 - text: twitter
   icon: social-twitter
   href: https://twitter.com/MichaelSnook
 - text: facebook
   icon: social-facebook
   href: https://facebook.com/michaelsnook
 - text: github
   icon: social-github
   href: https://github.com/michaelsnook
 - text: "CC0 1.0"
   icon: closed-caption
   href: https://github.com/michaelsnook/snook.pub/blob/gh-pages/LICENSE
 - text: "by me"
